# Generated by Django 3.2.6 on 2021-08-07 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=12)),
                ('limit_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('side', models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=4)),
                ('valid_until', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
